//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appiPedidos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvitacionPedidoGustoEmpanadaUsuario
    {
        public int IdInvitacionPedidoGustoEmpanadaUsuario { get; set; }
        public int IdPedido { get; set; }
        public int IdGustoEmpanada { get; set; }
        public int IdUsuario { get; set; }
        public int Cantidad { get; set; }
    
        public virtual GustoEmpanada GustoEmpanada { get; set; }
        public virtual Pedido Pedido { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
